# Generated by Django 3.1.1 on 2020-10-10 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_friendrequest'),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMembers',
            new_name='ChatMember',
        ),
    ]
